### ISSUE TITLE
Get the style from api.tilecloud.io

### ISSUE THREAD

**Issue by miya0001** [tilecloud/tilecloud.js#4]
It looks that tilecloud.js contains the JSON for all styles.
Let's get style from API.

Example:
https://api.tilecloud.io/v1/styles/osm-bright?key=1111

And also could you set style as HTML attribute like following?

```
<div 
  class="tilecloud"
  style="osm-bright"
  ...
>
```

It would be very nice if users can set their own styles.
So the value of stye should be able to set URL to their style.

How do you think?

**Comment by kamataryo** [comment]
@miya0001 How about to use data attributes insted of `style="osm-bright"`?
```html
    <div
      class="tilecloud"
      data-style="osm-bright"
      data-lat="35.681"
      data-lng="139.767"
      data-zoom="12"
    ></div>
```

**Comment by miya0001** [comment]
Thanks! 😊
