### ISSUE TITLE
What does the tilecloud=true mean?

### ISSUE THREAD

**Issue by miya0001** [tilecloud/tilecloud.js#5]
What does the `tilecloud=true` mean?

**Comment by kamataryo** [comment]
The script traverses the given html and finds API key from`<script>`.
The apiKey passed to the script under tilecloud.io is recognizable, like:
https://api.tilecloud.io/v1/tilecloud.js?apiKey=xxx
However, if user copies and renames the tilecloud.js, it will be difficult to determine whether apiKey query is for tilecloud.io.
- https//example.com/map.js?apiKey=xxx

The query `tilecloud=true` is only needed for external domains and  tells tilecloud.js the `apiKey=xxx` given together is yours.

**Comment by kamataryo** [comment]
API key is recognizable:
- https://api.tilecloud.io/*/tilecloud.js?apiKey=xxx
- https://example.com/script.js?tilecloud=true&apiKey=xxx

API key is not recognizable:
- https://example.com/script.js?apiKey=xxx
