### ISSUE TITLE
Undefined key for `/sources` API

### ISSUE THREAD

**Issue by miya0001** [tilecloud/tilecloud.js#6]
I got a problem as follows.

```
{
  "status": 403,
  "url": "https://api.tilecloud.io/v1/sources?key=undefined",
  "name": "e",
  "message": "Forbidden"
}
```

**Comment by kamataryo** [comment]
It seems that tilecloud.js couldn't retrieve API key at the client side. tilecloud.js accepts `apiKey`, not `key` parameter so far.
However, it is reasonable that tilecloud.js accepts the `key` parameter as same as other endpoints.
